language: swift
osx_image: xcode9.4
xcode_project: MyMovies.xcodeproj
xcode_scheme: MyMoviesTests
xcode-sdk: iphonesimulator11.4
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - carthage bootstrap
before_deloy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
